### ISSUE TITLE
JOIN tasks get stuck in IN_PROGRESS status

### ISSUE THREAD

**Issue by HenryLauu** [Netflix/conductor#1957]
I have a workflow with dynamic fork followed by join, the join task stays in IN_PROCESS after all forked task were finished.

**Comment by imaffe** [comment]
Can you provide some configuration files (include the workflow + task definitions) and perhaps some logs ? Thanks so much ~

**Comment by HenryLauu** [comment]
{
   "taskType": "JOIN",
   "status": "IN_PROGRESS",
   "inputData": {
      "joinOn": [
         "202009190001",
         "202009280001",
         "202009280002",
         "202009280003",
         "202009280004",
         "202009180005",
         "202010090006",
         "202010120007",
         "202010130008",
         "202010200002",
         "202010200005",
         "202010200006",
         "202010200007",
         "202010200008",
         "202010200009",
         "202010200010",
         "202010200011",
         "202010220002",
         "202010230001",
         "202010260001",
         "202010270009",
         "202010270011",
         "202010270015",
         "202010280001",
         "202010280002",
         "202010310001",
         "202010200004",
         "202011050001",
         "202011060001",
         "202011100001"
      ]
   },
   "referenceTaskName": "join",
   "retryCount": 0,
   "seq": 33,
   "pollCount": 0,
   "taskDefName": "JOIN",
   "scheduledTime": 1605007571969,
   "startTime": 1605007572051,
   "endTime": 1605007623032,
   "updateTime": 1605008302748,
   "startDelayInSeconds": 0,
   "retried": false,
   "executed": false,
   "callbackFromWorker": true,
   "responseTimeoutSeconds": 0,
   "workflowInstanceId": "7a96bbfe-87c3-4bce-ae78-6b8a00832f70",
   "workflowType": "",
   "taskId": "9c9010ab-6089-4922-8ecc-0c82c8c62382",
   "callbackAfterSeconds": 0,
   "outputData": {
      "202011060001": {},
      "202010260001": {},
      "202010200002": {},
      "202010200005": {},
      "202010090006": {},
      "202010130008": {},
      "202010200006": {},
      "202010200004": {},
      "202010270009": {},
      "202010280002": {},
      "202010230001": {},
      "202010280001": {},
      "202010200010": {},
      "202010200011": {},
      "202010310001": {},
      "202010200009": {},
      "202010270015": {},
      "202010200007": {},
      "202010200008": {},
      "202010220002": {},
      "202009280003": {},
      "202009180005": {},
      "202009280004": {},
      "202010270011": {},
      "202009280001": {},
      "202009280002": {},
      "202011050001": {},
      "202011100001": {},
      "202010120007": {},
      "202009190001": {}
   },
   "workflowTask": {
      "name": "JOIN",
      "taskReferenceName": "join",
      "inputParameters": {
         "joinOn": []
      },
      "type": "JOIN",
      "decisionCases": {},
      "defaultCase": [],
      "forkTasks": [],
      "startDelay": 0,
      "joinOn": [],
      "optional": false,
      "taskDefinition": {
         "ownerApp": "",
         "updateTime": 1602915778945,
         "updatedBy": "",
         "name": "JOIN",
         "description": "Join task",
         "retryCount": 0,
         "timeoutSeconds": 36000,
         "inputKeys": [
            "joinOn"
         ],
         "outputKeys": [],
         "timeoutPolicy": "TIME_OUT_WF",
         "retryLogic": "FIXED",
         "retryDelaySeconds": 5,
         "responseTimeoutSeconds": 36000,
         "inputTemplate": {
            "joinOn": "[]"
         },
         "rateLimitPerFrequency": 0,
         "rateLimitFrequencyInSeconds": 1,
         "ownerEmail": "",
         "pollTimeoutSeconds": 36000
      },
      "defaultExclusiveJoinTask": [],
      "asyncComplete": false,
      "loopOver": []
   },
   "rateLimitPerFrequency": 0,
   "rateLimitFrequencyInSeconds": 0,
   "workflowPriority": 0,
   "iteration": 0,
   "taskDefinition": {
      "present": true
   },
   "loopOverTask": false,
   "queueWaitTime": 82,
   "taskStatus": "IN_PROGRESS",
   "logs": []
}

**Comment by HenryLauu** [comment]
poll count is zero but status is in progress

**Comment by HenryLauu** [comment]
the task completed after i restart conductor server

**Comment by HenryLauu** [comment]
@alexnetflix would you pls assign someone to figure out what's going on ? I had this issues several times

**Comment by apanicker-nflx** [comment]
@HenryLauu can you please provide your workflow definition to help us recreate this issue? Thanks.

**Comment by HenryLauu** [comment]
Sorry I can paste the workflow here because of business constraints. Buy you can reproduce this problem by retrying a failed dynamic fork join workflow.

**Comment by HenryLauu** [comment]
@apanicker-nflx I think this is a serious bug, may I know who is the main contributor to this ?

**Comment by kishorebanala** [comment]
@HenryLauu IN_PROGRESS is the default state for JOIN task, when it starts it's lifecycle (because it is a synchronous system task), which answers why the poll count is 0. 

The execute logic of JOIN task is rather simple, which verifies if the task should reach terminal state on each run: https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/tasks/Join.java#L42

Can you confirm if the execute is called at all for this workflow, and if so, why it is failing to update the JOIN task please?

**Comment by HenryLauu** [comment]
I am absolutely sure about this issue, here is how to reproduce:
1) define a dynamic fork join workflow
2) failed one of the forked task, the join task turns to CANCELLED
3) retry the workflow, join task turns to IN_PROGRESS, all forked tasks complete but join task always stays IN_PROGRESS, the listener is working on in until i restart the conductor server

**Comment by apanicker-nflx** [comment]
Thanks for the steps, we will try to reproduce this issue and fix this soon. In the meantime, we would also welcome a PR with the fix if you get to this sooner. Thanks. 

PS. Labeling this as a bug for visibility.

**Comment by HenryLauu** [comment]
Hi @apanicker-nflx @kishorebanala I am trying to figure out what's going on here. It seems that the Workflow Executor does not keep monitoring the JOIN task. any suggestion about further investigation?

**Comment by HenryLauu** [comment]
update: I used zookeeper as distributed lock before. everything goes well after removing lock.

**Comment by kishorebanala** [comment]
@HenryLauu From your comment above: https://github.com/Netflix/conductor/issues/1957#issuecomment-744927453,
is there any chance the WorkflowExecutor is unable to obtain the lock from Zookeeper after retry?

**Comment by apanicker-nflx** [comment]
@HenryLauu this has been fixed as part of #2125

**Comment by BrandonDotLin** [comment]
@apanicker-nflx Seems this issue still exits in version 3.8.3。 The join task of dynamic fork stuck in IN-PROGRESS forever, nothing happen by trying call decide api or repair api

**Comment by autodidactic** [comment]
i see this issue still exists in 3.11.3

any PR request as to when it was fixed?

![Uploading conductor-Join_3.11.3.JPG…]()

**Comment by autodidactic** [comment]
`{
  "taskType": "JOIN",
  "status": "COMPLETED",
  "inputData": {
    "joinOn": [
      "dfas_splk_log_extr_requester_query1_ref1",
      "dfas_splk_log_extr_requester_query1_ref2",
      "dfas_splk_log_extr_requester_query1_ref3",
      "dfas_splk_log_extr_requester_query2_ref1",
      "dfas_splk_log_extr_requester_query2_ref2",
      "dfas_splk_log_extr_requester_query2_ref3"
    ]
  },
  "referenceTaskName": "join_request_ref",
  "retryCount": 0,
  "seq": 10,
  "pollCount": 0,
  "taskDefName": "JOIN",
  "scheduledTime": 1664827650617,
  "startTime": 1664827650975,
  "endTime": 1664827660811,
  "updateTime": 1664827650975,
  "startDelayInSeconds": 0,
  "retried": false,
  "executed": true,
  "callbackFromWorker": true,
  "responseTimeoutSeconds": 0,
  "workflowInstanceId": "70c9b2ad-d241-41b3-9703-e1c38daf3df2",
  "workflowType": "dfas-splunk-log-extr-wf",
  "taskId": "a7386628-744d-43df-a343-cf23f337708e",
  "callbackAfterSeconds": 0,
  "outputData": {
    "dfas_splk_log_extr_requester_query1_ref2": {
      "source": "QUANTUM",
      "sid": "1664827656.33348_046CD4EF-1E10-42AA-8CF2-1DB5DD171CE5"
    },
    "dfas_splk_log_extr_requester_query1_ref1": {
      "source": "QUANTUM",
      "sid": "1664827652.33344_046CD4EF-1E10-42AA-8CF2-1DB5DD171CE5"
    },
    "dfas_splk_log_extr_requester_query2_ref1": {
      "source": "CYBER",
      "sid": "1664827653.86354_EBC301CE-1E29-4D4B-B980-210762DFE089"
    },
    "dfas_splk_log_extr_requester_query2_ref2": {
      "source": "CYBER",
      "sid": "1664827659.86356_EBC301CE-1E29-4D4B-B980-210762DFE089"
    },
    "dfas_splk_log_extr_requester_query2_ref3": {
      "source": "CYBER",
      "sid": "1664827657.86355_EBC301CE-1E29-4D4B-B980-210762DFE089"
    },
    "dfas_splk_log_extr_requester_query1_ref3": {
      "source": "QUANTUM",
      "sid": "1664827655.33346_046CD4EF-1E10-42AA-8CF2-1DB5DD171CE5"
    }
  },
  "workflowTask": {
    "name": "join_request",
    "taskReferenceName": "join_request_ref",
    "inputParameters": {},
    "type": "JOIN",
    "startDelay": 0,
    "optional": false,
    "asyncComplete": false
  },
  "rateLimitPerFrequency": 0,
  "rateLimitFrequencyInSeconds": 0,
  "workflowPriority": 0,
  "iteration": 0,
  "subworkflowChanged": false,
  "taskDefinition": null,
  "queueWaitTime": 358,
  "loopOverTask": false
}`

**Comment by autodidactic** [comment]
> @apanicker-nflx Seems this issue still exits in version 3.8.3。 The join task of dynamic fork stuck in IN-PROGRESS forever, nothing happen by trying call decide api or repair api

The issue is fixed in version 3.13.3
