### ISSUE TITLE
Conductor UI - displaying logs does not work

### ISSUE THREAD

**Issue by odedlevy02** [Netflix/conductor#2692]
When trying to get logs using the conductor UI, it looks like the URL used to get the logs from the server is wrong - causing the Logs tab to always remain empty.

I have compiled the conductor server and client from the latest git version. 
I am creating a very simple task of type SIMPLE and adding logs when updating the task.
If I use Conductor server swagger api:  '/api/tasks/{taskId}/log' - then I can see my logs
When I try to use the conductor UI by selecting the Logs tab I will always get a message stating: 'No logs available'.
When opening the network to see the API used to get the logs I can see the following:
http://localhost:5000/**api/api**/tasks/<task id> (404 not found) 
Apparently the code is appending api twice to the url and therefore getting a 404 error

**Comment by howaric** [comment]
Hi @odedlevy02 , this bug was fixed in v3.4.0, you can upgrade the UI and have a try, thanks.

**Comment by odedlevy02** [comment]
Thanks but I have taken the latest version with tag v3.4.1 and v2.31.7 (latest main branch) and yet the bug still remains.
I am building a docker image using the docker compose file supplied in folder docker. Building ( docker-compose build ) and running (docker-compose up)

**Comment by odedlevy02** [comment]
Thanks. It works
